### ISSUE TITLE
Wrong string quotation character 

### ISSUE THREAD

**Issue by greschd** [ansys/pyansys-cheat-sheet#34]
The string quotation character e.g. in the PyMAPDL cheat sheet code is wrong:
![image](https://github.com/ansys/pyansys-cheat-sheet/assets/5692808/26c791f6-108b-4355-a50f-622e25ed57f6)

When copy/pasting, this is the result:
```
jname=’user_jobname’
path=’<path of directory>’
```
should be

```
jname='user_jobname'
path='<path of directory>'
```

From quick googling, it seems we need to add 

```tex
\lstset{upquote=true}
```
to the preamble. If that turns out not to be correct, I can dive into my archives to see how it was done in other projects.

**Comment by Revathyvenugopal162** [comment]
Thanks for pointing this @greschd . let me try to add the style library.
